# Generated by Django 4.2.7 on 2024-02-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], help_text='Select Preferred Method of Contact', max_length=100)),
                ('business_type', models.CharField(choices=[('aero', 'Aerospace'), ('agric', 'Agriculture'), ('auto', 'Automotive'), ('bank', 'Banking'), ('biotech', 'Biotechnology'), ('chem', 'Chemicals'), ('const', 'Construction'), ('edu', 'Education'), ('energy', 'Energy'), ('ent', 'Entertainment'), ('fashion', 'Fashion'), ('finance', 'Financial Services'), ('f&b', 'Food and Beverage'), ('govt', 'Government'), ('health', 'Healthcare'), ('hos', 'Hospitality'), ('it', 'Information Technology (IT)'), ('ins', 'Insurance'), ('legal', 'Legal'), ('manu', 'Manufacturing'), ('media', 'Media'), ('mining', 'Mining'), ('pharm', 'Pharmaceuticals'), ('real', 'Real Estate'), ('retail', 'Retail'), ('telecoms', 'Telecommunications'), ('transport', 'Transportation'), ('tt', 'Travel and Tourism'), ('util', 'Utilities'), ('who', 'Wholesale'), ('others', 'Others')], help_text='Select Your Industry Type', max_length=100)),
                ('service_requested', models.CharField(choices=[('sd', 'Software Development'), ('wd', 'Web Development'), ('md', 'Mobile App Development'), ('it', 'IT Consulting'), ('dm', 'Digital Marketing'), ('seo', 'Search Engine Optimization (SEO)'), ('cm', 'Content Marketing'), ('smm', 'Social Media Marketing'), ('gd', 'Graphic Design'), ('ecomm', 'E-commerce Development'), ('ns', ' Network Services')], help_text='Select The Project You Need Done', max_length=100)),
                ('image', models.FileField(upload_to='file_uploads/')),
                ('message', models.TextField()),
            ],
        ),
    ]
