# Generated by Django 4.2.7 on 2024-02-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='file_uploaded',
        ),
    ]
