# Generated by Django 4.2.7 on 2024-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_image_services_file_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
