# Generated by Django 4.2.7 on 2023-12-20 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_creation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateProject',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='CreateProjectComment',
            new_name='ProjectComment',
        ),
    ]
