# Generated by Django 4.2.7 on 2023-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0002_rename_createproject_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomment',
            old_name='blog_post',
            new_name='project',
        ),
    ]
