# Generated by Django 4.2.7 on 2023-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0003_rename_blog_post_projectcomment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
