# Generated by Django 4.2.7 on 2023-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0004_alter_projectcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='content',
            field=models.TextField(),
        ),
    ]
