# Generated by Django 4.2.7 on 2024-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0005_alter_projectcomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/images/default/default.jpg', upload_to='project_images/uploads/% Y/% M/% D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
