# Generated by Django 4.2.7 on 2024-01-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0006_project_image_alter_project_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/images/project_images/default.jpg', upload_to='project_images/uploads/%Y/%m-%d/'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='project_creation.project'),
        ),
    ]
