# Generated by Django 4.2.7 on 2024-02-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_social_media_handles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('tiktok', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media_handles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media_handles',
            field=models.ManyToManyField(to='users.socialmediahandles'),
        ),
    ]
