# Generated by Django 4.2.7 on 2024-02-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_socialmediahandles_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediahandles',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='socialmediahandles',
            name='x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='X'),
        ),
    ]
