# Generated by Django 4.2.7 on 2024-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpostcomment_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='images/blog_images/default.png/', upload_to='images/blog_images/uploads/%Y/%m-%d'),
        ),
    ]
