# Generated by Django 4.2.7 on 2024-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='author',
            field=models.CharField(),
        ),
    ]
