# Generated by Django 4.2.7 on 2024-03-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpostcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
    ]
